import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AnnouncementBar from '@/components/AnnouncementBar';
import TopNav from '@/components/TopNav';
import Banner from '@/components/Banner';
// import SlidePortion from '@/components/SlidingComponent/SlidePortion';
import SlidingSection from '@/components/SlidingComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AnnouncementBar announcement="This is an announcement" />
				<TopNav />
				<Banner />
				<SlidingSection />
				{children}
			</body>
		</html>
	);
}
